name: Run unit tests

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: coverage run -m pytest

      - name: Ensure minimum coverage
        run: coverage report --omit=tests/* --fail-under=80 -m
